# DiploDatos 2025- Mentoría " ¿Cómo clasfico a mis clientes? ML aplicado a un caso de negocio financiero"

## <font color=blue> Trabajo Practico N° 1 

##  Mentoría " Customizing offers: ¿Cómo clasifico a mis clientes? Machine Learning aplicado a un caso de negocio financiero"

## 1.	Familiarización con el dataset:

Para ello se deberá interpretar la documentación brindada donde se detalle el significado de cada variable, posteriormente se deberá importar los datos, analizar su estructura, tipos de campos, ver si hay datos faltantes.

## 2.	Interpretando el dataset
¿Qué tipo de variables tenemos?, categóricas, numéricas, discretas, continuas?  

Brindar los estadisticos descriptivos, media, mediana, percentiles, de comentarios de los mismos.

¿Hay clientes duplicados?, ¿Hay datos nulos? ¿A qué se puede deber? 

¿Hay outliers?  ¿A qué se puede deber?

## 3.	Análisis y Visualización de los datos


Para un buena predicción/segmentación es necesario realizar un buen análisis descriptivo, exploración de los datos considerando su tipo y valores definidos y tener acabado conocimiento de que representa cada uno de ellos.

Para los datos numéricos realizar una breve descripción de los mismos, analizando sus medias, percentiles, outliers. 
Mientras que para las variables categóricas realizar un análisis de transaccionalidad vrs Estado Civil, grupo_cliente, UsaPlataforma, etc. Realizar un análisis de variabilidad de la transaccionalidad respecto de estas variables y otras más que puedan considerar de utilidad para el entendimiento del comportamiento del cliente.

También para este análisis se puede considerar las variables CROSS_IND y CROSS_EMPR que nos indican cantidad de productos que ya tienen los clientes, ello nos pueda dar una pista de que tan dispuestos son de tener varios de los productos.

Algunas de las preguntas que nos podríamos realizar son las siguientes:

¿Como es la distribucion del ingreso promedio, asimetrica, simetrica? De un comentario al respecto.

¿Quien tiene mas productos? recordar que para ver esto es necesario utilizar las variables Cross_Ind y  Cross_Empr, luego del analisis, realizar una conclusion, ¿están bien calculadas acorde a su definición? Estas ayudaran a la hora de realizar el modelo?

¿Es relevante el dato capita? ¿ como se comporta con respecto a a la transaccionalidad?

Al dato Edad, ¿cómo lo consideramos? Discreto o Continuo? Grafique su distribucion y de breve comentario.

¿Existe algún tipo de relación entre la edad del cliente y el uso de plataforma?

¿A qué fecha son los datos? ¿Fue correcto la selección de este periodo para el análisis? 

¿Existe algún tipo de relación entre la cantidad de productos alcanzados  y el nivel de ingresos?

¿Los datos nos permitirán realizar una clasificación de los clientes en función de sus transacciones? ¿O en función de los productos que tiene? ¿Cual sera la mas adecuada?

¿Cuál es el servicio/producto más utilizado?, recordar que esto lo podemos obtener de las variables Tiene_i para los productos y de las variables indicadas en la sección Información sobre Cantidad de Transaccionalidad Realizada.

¿Qué tipos de clientes, con respecto a la segmentación dada (segmento_sueldo y segmento_bancas, subgrupo) utilizan más nuestros productos?

¿La edad, estado civil, sexo son datos relevantes? ¿ Se puede ver alguna correlacion con los productos/servicios?

¿El ingreso promedio de los últimos 6 meses, se puede considerar como relevante? Nos podrá ayudar en nuestra segmentación? 

¿Qué producto/servicio se ha utilizado más? Hay alguna relación con el periodo (¿mes y año utilizados?)

¿Qué clientes han realizado más depósitos?

¿Sobre las transferencia, que tipo de trasferencia se ha realizado más? ¿Enviada o Recibida? Y en cuento a los montos cual ha sido el mayor?  

¿Qué tipos de clientes realizan operatoria de inversión en títulos/FCI?

Realizar un ranking de los 10 clientes con mas productos y analizar su transaccionalidad.

¿Como es la distribución de los datos cross_ind, cross_empr con respecto a las variables de transaccionalidad, por ejemplo las de compras, las de transferencias observamos que muchos de nuestros clientes que tienen más de un producto utiliza estos servicios?

Como es el comportamiento de aquellos clientes que han realizado Plazo Fijo, con respecto al resto de la transaccionalidad, ¿realizan también inversión en Titulos/FCI? Realizar análisis similares para el resto de la operatividad.

Basándose en los análisis anteriores, realice una matriz de correlacion entre las variables.

Puede ya definir cuales serán las variables mas interesantes que contribuirán al modelo.

# Importar librerías necesarias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stat
import scipy.stats as st
from statistics import stdev
from scipy.stats import t
import datetime
#import missingno as msno
import seaborn

seaborn.set_context('talk')
sns.set_context('talk')

# Seteo de displays
pd.set_option('display.max_columns',10000)
pd.set_option('display.max_rows',10000)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
pd.options.display.max_columns = None # para que no recorte las columnas

# Leer el dataset

In [2]:
# Importamos el datset que definimmos

df = pd.read_csv ("muestra.txt", sep=';', encoding='latin-1')

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36811 entries, 0 to 36810
Data columns (total 90 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   cliente                          36811 non-null  int64
 1   Periodo_cliente                  36811 non-null  int64
 2   sexo                             36809 non-null  object
 3   estado_civil                     36809 non-null  object
 4   edad                             36811 non-null  int64
 5   usaplataforma_U3M                36811 non-null  object
 6   ingprm_U6M                       36811 non-null  float64
 7   capita                           36811 non-null  object
 8   grupo_cliente                    36811 non-null  object
 9   subgrupo                         36811 non-null  object
 10  relacion                         36811 non-null  object
 11  fum                              36811 non-null  int64
 12  segmento_sueldos                 36811 non-null  object
 13  segmento_bancas                  36811 non-null  object
 14  tiene_i_cbesa                    32813 non-null  float64
 15  tiene_i_cs                       32813 non-null  float64
 16  tiene_i_pr_hip                   32813 non-null  float64
 17  tiene_i_pr_pers                  32813 non-null  float64
 18  tiene_i_prep                     32813 non-null  float64
 19  tiene_i_se_patr                  32813 non-null  float64
 20  tiene_i_visa                     32813 non-null  float64
 21  tiene_i_tj_soc                   32813 non-null  float64
 22  tiene_e_ac_cc                    32813 non-null  float64
 23  tiene_e_fact                     32813 non-null  float64
 24  tiene_e_liq_com                  32813 non-null  float64
 25  tiene_i_seg_vida                 32813 non-null  float64
 26  tiene_e_tc_agro                  32813 non-null  float64
 27  tiene_e_tc_corpo                 32813 non-null  float64
 28  tiene_e_tc_flota                 32813 non-null  float64
 29  cross_ind                        32813 non-null  float64
 30  cross_empr                       32813 non-null  float64
 31  sldo_PF                          32813 non-null  float64
 32  sldo_CC_pesos                    32813 non-null  float64
 33  sldo_CC_Prod_MB                  32813 non-null  float64
 34  sldo_FCI                         32813 non-null  float64
 35  sldo_CA_pesos                    32813 non-null  float64
 36  Credito_Acreditacion             21920 non-null  float64
 37  Credito_Cheque                   429 non-null    float64
 38  Credito_Cuenta                   72 non-null     float64
 39  Credito_Deposito                 3178 non-null   float64
 40  Credito_Embargo                  9 non-null      float64
 41  Credito_OperacionCambio          465 non-null    float64
 42  Credito_Operatoria               34397 non-null  float64
 43  Credito_PlazoFijo                1845 non-null   float64
 44  Credito_Prestamo                 349 non-null    float64
 45  Credito_TarjetaCredito           332 non-null    float64
 46  Credito_Titulos_FCI              81 non-null     float64
 47  Credito_TransferenciaRecibida    18436 non-null  float64
 48  Debito_CajadeSeguridad           6 non-null      float64
 49  Debito_Cheque                    216 non-null    float64
 50  Debito_Compras                   17395 non-null  float64
 51  Debito_Cuenta                    248 non-null    float64
 52  Debito_Embargo                   15 non-null     float64
 53  Debito_Extraccion                21401 non-null  float64
 54  Debito_OperacionCambio           465 non-null    float64
 55  Debito_Operatoria                11570 non-null  float64
 56  Debito_PlazoFijo                 1834 non-null   float64
 57  Debito_Prestamo                  3979 non-null   float64
 58  Debito_Seguro                    2688 non-null   float64
 59  Debito_TarjetaCredito            8654 non-null   float64
 60  Debito_Titulos_FCI               80 non-null     float64
 61  Debito_TransferenciaEnviada      20129 non-null  float64
 62  Debito_Transporte                829 non-null    float64
 63  k_Credito_Acreditacion           36811 non-null  int64
 64  k_Credito_Cheque                 36811 non-null  int64
 65  k_Credito_Cuenta                 36811 non-null  int64
 66  k_Credito_Deposito               36811 non-null  int64
 67  k_Credito_Embargo                36811 non-null  int64
 68  k_Credito_OperacionCambio        36811 non-null  int64
 69  k_Credito_Operatoria             36811 non-null  int64
 70  k_Credito_PlazoFijo              36811 non-null  int64
 71  k_Credito_Prestamo               36811 non-null  int64
 72  k_Credito_TarjetaCredito         36811 non-null  int64
 73  k_Credito_Titulos_FCI            36811 non-null  int64
 74  k_Credito_TransferenciaRecibida  36811 non-null  int64
 75  k_Debito_CajadeSeguridad         36811 non-null  int64
 76  k_Debito_Cheque                  36811 non-null  int64
 77  k_Debito_Compras                 36811 non-null  int64
 78  k_Debito_Cuenta                  36811 non-null  int64
 79  k_Debito_Embargo                 36811 non-null  int64
 80  k_Debito_Extraccion              36811 non-null  int64
 81  k_Debito_OperacionCambio         36811 non-null  int64
 82  k_Debito_Operatoria              36811 non-null  int64
 83  k_Debito_PlazoFijo               36811 non-null  int64
 84  k_Debito_Prestamo                36811 non-null  int64
 85  k_Debito_Seguro                  36811 non-null  int64
 86  k_Debito_TarjetaCredito          36811 non-null  int64
 87  k_Debito_Titulos_FCI             36811 non-null  int64
 88  k_Debito_TransferenciaEnviada    36811 non-null  int64
 89  k_Debito_Transporte              36811 non-null  int64
dtypes: float64(50), int64(31), object(9)
memory usage: 25.3+ MB
None

In [4]:
df.head()

,cliente,Periodo_cliente,sexo,estado_civil,edad,usaplataforma_U3M,ingprm_U6M,capita,grupo_cliente,subgrupo,relacion,fum,segmento_sueldos,segmento_bancas,tiene_i_cbesa,tiene_i_cs,tiene_i_pr_hip,tiene_i_pr_pers,tiene_i_prep,tiene_i_se_patr,tiene_i_visa,tiene_i_tj_soc,tiene_e_ac_cc,tiene_e_fact,tiene_e_liq_com,tiene_i_seg_vida,tiene_e_tc_agro,tiene_e_tc_corpo,tiene_e_tc_flota,cross_ind,cross_empr,sldo_PF,sldo_CC_pesos,sldo_CC_Prod_MB,sldo_FCI,sldo_CA_pesos,Credito_Acreditacion,Credito_Cheque,Credito_Cuenta,Credito_Deposito,Credito_Embargo,Credito_OperacionCambio,Credito_Operatoria,Credito_PlazoFijo,Credito_Prestamo,Credito_TarjetaCredito,Credito_Titulos_FCI,Credito_TransferenciaRecibida,Debito_CajadeSeguridad,Debito_Cheque,Debito_Compras,Debito_Cuenta,Debito_Embargo,Debito_Extraccion,Debito_OperacionCambio,Debito_Operatoria,Debito_PlazoFijo,Debito_Prestamo,Debito_Seguro,Debito_TarjetaCredito,Debito_Titulos_FCI,Debito_TransferenciaEnviada,Debito_Transporte,k_Credito_Acreditacion,k_Credito_Cheque,k_Credito_Cuenta,k_Credito_Deposito,k_Credito_Embargo,k_Credito_OperacionCambio,k_Credito_Operatoria,k_Credito_PlazoFijo,k_Credito_Prestamo,k_Credito_TarjetaCredito,k_Credito_Titulos_FCI,k_Credito_TransferenciaRecibida,k_Debito_CajadeSeguridad,k_Debito_Cheque,k_Debito_Compras,k_Debito_Cuenta,k_Debito_Embargo,k_Debito_Extraccion,k_Debito_OperacionCambio,k_Debito_Operatoria,k_Debito_PlazoFijo,k_Debito_Prestamo,k_Debito_Seguro,k_Debito_TarjetaCredito,k_Debito_Titulos_FCI,k_Debito_TransferenciaEnviada,k_Debito_Transporte
0,1001,202203,F,Soltero/a,29,NO,22555.130000,ESPECIAL,I6,Con producto Social,TIT,20220331,OTROS,OTROS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3084.580000,43108.730000,NaN,NaN,NaN,NaN,NaN,1181.400000,NaN,NaN,NaN,NaN,25300.000000,NaN,NaN,3937.990000,NaN,NaN,61700.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298.000000,NaN,4,0,0,0,0,0,2,0,0,0,0,8,0,0,1,0,0,10,0,0,0,0,0,0,0,2,0
1,1001,202204,F,Soltero/a,29,NO,22555.130000,ESPECIAL,I6,Con producto Social,TIT,20220429,OTROS,OTROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37765.970000,NaN,NaN,44000.000000,NaN,NaN,411.260000,NaN,NaN,NaN,NaN,7300.000000,NaN,NaN,1370.000000,NaN,NaN,38500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47398.000000,NaN,4,0,0,3,0,0,3,0,0,0,0,4,0,0,1,0,0,8,0,0,0,0,0,0,0,4,0
2,1001,202205,F,Soltero/a,29,NO,22555.130000,ESPECIAL,I6,Con producto Social,TIT,20220530,OTROS,OTROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47423.210000,NaN,NaN,3300.000000,NaN,NaN,600.460000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.000000,NaN,NaN,40000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10898.000000,NaN,4,0,0,1,0,0,3,0,0,0,0,0,0,0,1,0,0,6,0,0,0,0,0,0,0,4,0
3,1001,202206,F,Soltero/a,29,NO,22555.130000,ESPECIAL,I6,Con producto Social,TIT,20220623,OTROS,OTROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51102.650000,NaN,NaN,NaN,NaN,NaN,1241.660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4137.990000,NaN,NaN,44000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3398.000000,NaN,4,0,0,0,0,0,5,0,0,0,0,0,0,0,2,0,0,4,0,0,0,0,0,0,0,2,0
4,1001,202207,F,Soltero/a,29,NO,22555.130000,ESPECIAL,I6,Con producto Social,TIT,20220722,OTROS,OTROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41771.720000,NaN,NaN,3000.000000,NaN,NaN,229.910000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,766.000000,NaN,NaN,36000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8398.000000,NaN,3,0,0,1,0,0,3,0,0,0,0,0,0,0,1,0,0,4,0,0,0,0,0,0,0,4,0

In [5]:
df.describe()

,cliente,Periodo_cliente,edad,ingprm_U6M,fum,tiene_i_cbesa,tiene_i_cs,tiene_i_pr_hip,tiene_i_pr_pers,tiene_i_prep,tiene_i_se_patr,tiene_i_visa,tiene_i_tj_soc,tiene_e_ac_cc,tiene_e_fact,tiene_e_liq_com,tiene_i_seg_vida,tiene_e_tc_agro,tiene_e_tc_corpo,tiene_e_tc_flota,cross_ind,cross_empr,sldo_PF,sldo_CC_pesos,sldo_CC_Prod_MB,sldo_FCI,sldo_CA_pesos,Credito_Acreditacion,Credito_Cheque,Credito_Cuenta,Credito_Deposito,Credito_Embargo,Credito_OperacionCambio,Credito_Operatoria,Credito_PlazoFijo,Credito_Prestamo,Credito_TarjetaCredito,Credito_Titulos_FCI,Credito_TransferenciaRecibida,Debito_CajadeSeguridad,Debito_Cheque,Debito_Compras,Debito_Cuenta,Debito_Embargo,Debito_Extraccion,Debito_OperacionCambio,Debito_Operatoria,Debito_PlazoFijo,Debito_Prestamo,Debito_Seguro,Debito_TarjetaCredito,Debito_Titulos_FCI,Debito_TransferenciaEnviada,Debito_Transporte,k_Credito_Acreditacion,k_Credito_Cheque,k_Credito_Cuenta,k_Credito_Deposito,k_Credito_Embargo,k_Credito_OperacionCambio,k_Credito_Operatoria,k_Credito_PlazoFijo,k_Credito_Prestamo,k_Credito_TarjetaCredito,k_Credito_Titulos_FCI,k_Credito_TransferenciaRecibida,k_Debito_CajadeSeguridad,k_Debito_Cheque,k_Debito_Compras,k_Debito_Cuenta,k_Debito_Embargo,k_Debito_Extraccion,k_Debito_OperacionCambio,k_Debito_Operatoria,k_Debito_PlazoFijo,k_Debito_Prestamo,k_Debito_Seguro,k_Debito_TarjetaCredito,k_Debito_Titulos_FCI,k_Debito_TransferenciaEnviada,k_Debito_Transporte
count,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,32813.000000,21920.000000,429.000000,72.000000,3178.000000,9.000000,465.000000,34397.000000,1845.000000,349.000000,332.000000,81.000000,18436.000000,6.000000,216.000000,17395.000000,248.000000,15.000000,21401.000000,465.000000,11570.000000,1834.000000,3979.000000,2688.000000,8654.000000,80.000000,20129.000000,829.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000,36811.000000
mean,2140.150444,202325.729918,39.339572,276023.006602,20214293.098992,0.407278,0.005425,0.010087,0.104349,0.057538,0.034681,0.069180,0.037180,0.003992,0.000183,0.009905,0.069149,0.000549,0.000000,0.000000,2.169628,0.235608,65583.629410,4545.644776,32.038330,2376.372688,86410.737886,254350.073254,538161.968182,97696.230556,151678.506211,3680.820000,5475.410839,8364.786195,899948.967859,1485693.442063,1379365.371386,480122.038889,339909.418268,278693.250000,1335512.670324,97519.176508,222404.128952,38721.013333,116745.333268,309101.881720,54263.843780,874671.998768,64428.794157,5289.369825,100441.313352,552112.688375,360534.378098,5193.426586,1.141235,0.023091,0.003749,0.375486,0.000244,0.014670,1.745266,0.080900,0.010214,0.373041,0.005270,3.922876,0.000163,0.050637,4.519899,0.028252,0.000489,3.281655,0.014697,2.315721,0.068566,0.238950,0.097580,0.454239,0.003206,5.315802,0.178316
std,708.148183,88.839850,12.210576,2208337.112257,567735.928394,0.491335,0.073453,0.099930,0.305717,0.232872,0.182974,0.253764,0.189206,0.063060,0.013521,0.099029,0.253712,0.023415,0.000000,0.000000,1.435155,0.516800,628826.869642,127464.620132,2941.854514,91546.382798,317541.248543,417140.823985,1274422.222853,161060.442287,380153.395993,6710.923021,83319.026903,54522.216284,2407459.076564,3478094.445968,2737776.089516,1162694.036572,972483.851653,226063.672327,1471137.603445,164737.364554,519064.237881,92783.309584,260260.922214,2392107.073360,210742.382672,2338641.596831,492751.142519,12904.823999,218228.557979,1212968.605876,978321.943615,7558.737647,1.215971,0.324428,0.099097,2.524264,0.015635,0.139280,3.023113,0.439526,0.108603,4.864123,0.143970,11.262078,0.012766,1.011340,8.370298,0.477321,0.025530,5.027471,0.139764,15.687029,0.349834,0.919383,0.385118,0.929747,0.077593,9.140453,1.862639
min,1001.000000,202203.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.180000,1249.570000,337.500000,0.090000,12.320000,1.000000,0.010000,103.890000,6000.000000,3.000000,0.030000,0.010000,79815.680000,1249.570000,0.150000,3.460000,12.320000,0.140000,0.120000,0.010000,1000.000000,0.120000,0.750000,0.090000,1000.000000,0.010000,59.350000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1517.000000,202212.000000,32.000000,5000.000000,20221026.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,840.950000,33606.720000,74658.000000,1000.000000,15000.000000,88.390000,100.000000,0.130000,109698.630000,100000.000000,146052.475000,17000.000000,30000.000000,109344.517500,300000.000000,11268.160000,6912.750000,486.590000,22000.000000,15600.000000,993.700000,101930.550000,5290.380000,774.012500,14873.802500,50974.535000,29176.400000,706.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2090.000000,202309.000000,34.000000,44379.000000,20230731.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9585.580000,102884.320000,166460.000000,32145.500000,43140.000000,667.570000,200.000000,1.290000,329232.880000,369130.000000,416231.925000,200000.000000,102000.000000,192766.815000,824500.000000,38256.630000,23551.665000,5000.000000,51000.000000,26700.000000,7766.080000,316194.520000,16517.920000,1676.090000,39500.620000,220000.000000,109400.000000,2170.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,2764.000000,202406.000000,43.000000,172907.000000,20240430.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52824.200000,288633.870000,444714.000000,125073.902500,137750.000000,5000.000000,200.000000,13.900000,868433.970000,1110000.000000,1304786.947500,400000.530000,323675.377500,440147.107500,1786321.767500,111629.850000,170662.360000,20951.670000,123000.000000,40250.000000,40657.577500,827900.000000,49053.810000,5064.000000,108449.740000,412500.000000,353995.400000,6290.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,6.000000,0.000000,0.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,0.000000
max,3354.000000,202502.000000,80.000000,129040652.000000,20250310.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,9.000000,6.000000,40162700.000000,15119400.000000,526001.000000,6693670.000000,9725360.000000,18071768.370000,17353408.470000,817728.850000,10020000.000000,20738.370000,1786337.250000,3734354.220000,31921506.840000,27255696.800000,20991928.630000,7474595.700000,53397985.300000,602665.900000,8091245.750000,3193354.360000,3575779.340000,359950.450000,10000000.000000,27255696.000000,16415348.250000,31000000.000000,28596032.880000,215089.360000,12727712.420000,7427172.000000,50264298.310000,63120.000000,14.000000,20.000000,5.000000,126.000000,1.000000,5.000000,130.000000,12.000000,3.000000,110.000000,10.000000,374.000000,1.000000,72.000000,108.000000,18.000000,2.000000,88.000000,5.000000,736.000000,8.000000,27.000000,6.000000,23.000000,4.000000,120.000000,71.000000